poetry : Traceback (most recent call last):
No linha:1 caractere:1
+ poetry run uvicorn app.main:app 2>&1 | Out-File -FilePath uvicorn_log ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::Strin 
   g) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\click\core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\click\core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\click\core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\click\core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\uvicorn\main.py", line 413, in main
    run(
    ~~~^
        app,
        ^^^^
    ...<45 lines>...
        h11_max_incomplete_event_size=h11_max_incomplete_event_size,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\uvicorn\main.py", line 580, in run
    server.run()
    ~~~~~~~~~~^^
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\uvicorn\server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
"C:\Users\Romulo\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", 
line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File 
"C:\Users\Romulo\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", 
line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File 
"C:\Users\Romulo\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", 
line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\uvicorn\server.py", line 71, in serve
    await self._serve(sockets)
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\uvicorn\server.py", line 78, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\uvicorn\config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File 
"C:\Users\Romulo\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", 
line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File 
"D:\Romulo\Documents\ProgramaþÒo\Oraculo\oraculo-plataforma\backend\app\main.py", 
line 2, in <module>
    from app.core.config import settings
  File "D:\Romulo\Documents\ProgramaþÒo\Oraculo\oraculo-plataforma\backend\app\core\co
nfig.py", line 24, in <module>
    settings = Settings()
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\pydantic_settings\main.py", line 188, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        **__pydantic_self__._settings_build_values(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<27 lines>...
        )
        ^
    )
    ^
  File "C:\Users\Romulo\AppData\Local\pypoetry\Cache\virtualenvs\oraculo-backend-C25Rf
8eY-py3.13\Lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, 
self_instance=self)
pydantic_core._pydantic_core.ValidationError: 7 validation errors for Settings
secret_key
  Extra inputs are not permitted [type=extra_forbidden, 
input_value='JpQPKur1AJpVJdtukr91k0UN...VTMoJS2XGMezmCrOOzpqg==', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden
algorithm
  Extra inputs are not permitted [type=extra_forbidden, input_value='HS256', 
input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden
access_token_expire_minutes
  Extra inputs are not permitted [type=extra_forbidden, input_value='10080', 
input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden
redis_url
  Extra inputs are not permitted [type=extra_forbidden, 
input_value='rediss://red-d2qqbmd6ubr...6379?ssl_cert_reqs=none', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden
celery_broker_url
  Extra inputs are not permitted [type=extra_forbidden, 
input_value='rediss://red-d2qqbmd6ubr...6379?ssl_cert_reqs=none', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden
celery_result_backend
  Extra inputs are not permitted [type=extra_forbidden, 
input_value='rediss://red-d2qqbmd6ubr...6379?ssl_cert_reqs=none', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden
database_url
  Extra inputs are not permitted [type=extra_forbidden, 
input_value='postgresql://postgres:kB...pabase.co:5432/postgres', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden
